name: Update Version Badge

on:
  push:
    branches:
      - master  # Change if using a different default branch

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version from build.gradle
        run: |
          VERSION_NAME=$(grep 'versionName ' app/build.gradle | awk -F '"' '{print $2}')
          VERSION_SUFFIX=$(grep 'versionNameSuffix ' app/build.gradle | awk -F '"' '{print $2}')
          FULL_VERSION="${VERSION_NAME}${VERSION_SUFFIX}"
          echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV

      - name: Update README Badge
        run: |
          BADGE_URL="https://img.shields.io/badge/version-${FULL_VERSION}-green"
          sed -i "s|!\[Version\](.*)|![Version](${BADGE_URL})|" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update version badge to ${FULL_VERSION}" || exit 0
          git push
